# This is a test & lint workflow

name: Test & Lint

# Controls when the action will run
on:
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-and-lint:
    name: Test & Lint job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      # Setup NodeJS
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Install project dependencies
      - name: Build
        run: yarn install

      # Run tests
      - name: Test
        run: yarn run test

      # Runs cdk synthesize command
      - name: Run cdk synthesize command
        run: yarn run cdk synthesize

      # Run linters
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          eslint_extensions: ts
          prettier: true
          prettier_extensions: ts
